services:
  - type: web
    name: books-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python create_sample_data.py
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/v1/health
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.11.6
    autoDeploy: true